# Generated by Django 3.1.4 on 2021-01-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210106_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('subj', models.CharField(choices=[('Python', 'Python'), ('JQUERY', 'jQuery'), ('JavaScript', 'JavaScript')], default='Python', max_length=10)),
                ('answer', models.TextField(blank=True, max_length=200, null=True)),
                ('easy', models.BooleanField(default=True)),
                ('medium', models.BooleanField(default=True)),
                ('hard', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
