# Generated by Django 3.1.4 on 2021-01-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210106_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='user',
            new_name='name',
        ),
    ]
