# Generated by Django 3.1.4 on 2021-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210106_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hard',
        ),
        migrations.RemoveField(
            model_name='question',
            name='medium',
        ),
        migrations.AddField(
            model_name='question',
            name='quetype',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
