# Generated by Django 3.1.4 on 2021-01-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_subject_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
