# Generated by Django 3.1.4 on 2021-01-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_delete_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
