# Generated by Django 3.1.4 on 2021-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subj',
            field=models.CharField(choices=[('Python', 'Python'), ('JQuery', 'JQuery'), ('HTML', 'HTML')], default='Python', max_length=10),
        ),
    ]
